### ISSUE TITLE
Does not build with zig 0.15.1

### ISSUE THREAD

**Issue by TheFeelTrain** [adworacz/zsmooth#17]
```
build.zig:14:18: error: no field or member function named 'addSharedLibrary' in 'Build'
    const lib = b.addSharedLibrary(.{
                ~^~~~~~~~~~~~~~~~~
/home/thefeeltrain/.local/share/zvm/0.15.1/lib/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
build.zig:14:18: note: method invocation only supports up to one level of implicit pointer dereferencing
build.zig:14:18: note: use '.*' to dereference pointer
```

**Comment by adworacz** [comment]
This will be part of the 0.13 release.
